"""Original, temporary R4 release fixture builder.

The builder deliberately creates all bytes at test time.  Nothing generated by
this module belongs in the repository.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from blockpedia.r3 import encode_rgba_png
from blockpedia.features import FEATURE_EXTRACTOR_VERSION, _normalized_hash, _oklab_and_lab
from blockpedia.releases import CHECK_CODES
from blockpedia.search import SEMANTIC_LIST_FIELDS, SEMANTIC_SCALAR_FIELDS, normalize_text


HASH = "sha256:" + "a" * 64
SOURCE_EXPORT = "export_20260818T120000Z"
RELEASE_ID = "rel_" + "1" * 32
RELEASE_BUILD_ID = "build_" + "2" * 32
RUN_ID = "run_fixture_r4"


def _canonical(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def _hash(payload: bytes) -> str:
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def _raw_hash(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _behavior(*, transparent: bool, emissive: bool = False, redstone: bool = False, support_below: bool = True) -> dict[str, Any]:
    return {
        "transparent": transparent,
        "emissive": emissive,
        "emission_level": 0,
        "passable": False,
        "waterloggable": False,
        "requires_support": False,
        "redstone_related": redstone,
        "support": {"above": "unknown", "below": support_below, "east": "unknown", "north": "unknown", "south": "unknown", "west": "unknown", "none": "unknown"},
    }


def _shape(signature: str, *, full: bool = True, height: float = 1.0) -> dict[str, Any]:
    return {"boxes": [{"min_x": 0, "min_y": 0, "min_z": 0, "max_x": 1, "max_y": height, "max_z": 1}], "signature": signature}


def _block(block_id: str, name_zh: str, name_en: str, default_state: str) -> dict[str, Any]:
    return {
        "schema_version": "block-record.v1", "export_id": SOURCE_EXPORT, "minecraft_version": "26.2", "block_id": block_id,
        "translation_key": "block." + block_id.removeprefix("minecraft:"), "official_names": {"zh_cn": name_zh, "en_us": name_en},
        "default_state_id": default_state, "properties": {}, "tags": [], "machine_facts": {"has_item": True, "has_block_entity": False},
        "source": {"type": "runtime", "minecraft_version": "26.2", "export_id": SOURCE_EXPORT, "exporter_version": "fixture-exporter", "stage": "EXPORT_REGISTRY"},
    }


def _state(state_id: str, block_id: str, behavior: dict[str, Any], shape: dict[str, Any], *, variant_id: str) -> dict[str, Any]:
    return {
        "schema_version": "state-record.v1", "export_id": SOURCE_EXPORT, "minecraft_version": "26.2", "state_id": state_id, "block_id": block_id,
        "properties": {}, "is_default": True, "legal_state": True, "shape": shape, "collision": shape, "behavior": behavior,
        "variant_ids": [variant_id], "mapping_status": "mapped", "failure_id": None,
        "source": {"type": "runtime", "minecraft_version": "26.2", "export_id": SOURCE_EXPORT, "exporter_version": "fixture-exporter", "stage": "EXPORT_REGISTRY"},
    }


def _variant(block_id: str, state_id: str, behavior: dict[str, Any], shape: dict[str, Any], *, classes: list[str], tags: list[str], qualification: str = "eligible", warning: str | None = None) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    suffix = block_id.removeprefix("minecraft:")
    color = [40, 120, 40, 255] if block_id.endswith("stone") else [80, 160, 220, 255] if block_id.endswith("glass") else [220, 180, 40, 255]
    preview = encode_rgba_png(512, 512, bytes(color * (512 * 512)))
    mask = encode_rgba_png(512, 512, bytes([255, 255, 255, 255] * (512 * 512)))
    render_metadata = {
        "schema_version": "render-metadata.v1", "variant_id": block_id, "width": 512, "height": 512, "format": "PNG-RGBA",
        "views": ["isometric", "front", "side", "top"], "fixture_id": "fixture-render", "fixture_version": "fixture.v1",
        "tint_sensitive": False, "baseline_biome": None, "mask": {"present": True, "format": "PNG-RGBA", "channel": "alpha", "threshold": 1},
    }
    render_hash = _hash(json.dumps(render_metadata, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8"))
    feature_geometry = {
        "is_full_cube": "full_cube" in classes,
        "_union_proven": True,
        "is_horizontal_sheet": "horizontal_sheet" in classes,
        "height": shape["boxes"][0]["max_y"],
    }
    red, green, blue = color[:3]
    oklab, lab = _oklab_and_lab(red, green, blue)
    feature = {
        "input_sha256": _normalized_hash([preview, mask, feature_geometry]),
        "feature_extractor_version": FEATURE_EXTRACTOR_VERSION,
        "mask_coverage": 1.0,
        "transparent_ratio": 0.0,
        "average_rgb": [round(red / 255, 8), round(green / 255, 8), round(blue / 255, 8)],
        "oklab": list(oklab),
        "lab": list(lab),
        "brightness": round((0.2126 * red + 0.7152 * green + 0.0722 * blue) / 255.0, 8),
        "saturation": round((max(red, green, blue) - min(red, green, blue)) / max(1, max(red, green, blue)), 8),
        "edge_density": round(1024 / (512 * 512 * 2), 8),
        "directionality": 0.0,
        "geometry_classes": list(classes),
        "machine_tags": sorted(set(tags), key=lambda value: value.encode("utf-8")),
    }
    geometry = {
        "geometry_signature": HASH, "collision_signature": HASH, "shape": shape, "collision": shape, "width": 1.0, "height": shape["boxes"][0]["max_y"], "depth": 1.0,
        "occupied_volume": shape["boxes"][0]["max_y"], "is_full_cube": "full_cube" in classes, "is_horizontal_sheet": "horizontal_sheet" in classes,
        "geometry_classes": classes, "feature_extractor_version": feature["feature_extractor_version"], "feature_input_sha256": feature["input_sha256"],
    }
    warnings = [warning] if warning else []
    variant = {
        "schema_version": "visual-variant-record.v1", "export_id": SOURCE_EXPORT, "minecraft_version": "26.2", "variant_id": block_id, "block_id": block_id,
        "canonical_state_id": state_id, "represented_state_ids": [state_id], "context": {"fixture_id": "fixture-render", "fixture_version": "fixture.v1", "rotatable": True, "canonical_orientation": None},
        "selection": {"state_policy_version": "state-policy.v1", "reason": "runtime default", "protected_dimensions": [], "folded_state_ids": [], "policy_override_id": None},
        "machine_facts": {"geometry": geometry, "behavior_fingerprint": HASH, "behavior_by_state": {state_id: behavior}, "machine_tags": tags},
        "render": {"render_policy_version": "render.v2", "preview_path": f"renders/minecraft/{suffix}/preview.png", "mask_path": f"renders/minecraft/{suffix}/mask.png", "render_metadata_path": f"renders/minecraft/{suffix}/render.json", "image_sha256": _hash(preview), "mask_sha256": _hash(mask), "render_metadata_sha256": render_hash},
        "annotation_refs": [], "override_refs": [], "qualification_review_refs": [], "candidate_qualification": qualification, "warnings": warnings,
        "source": {"type": "machine", "minecraft_version": "26.2", "export_id": SOURCE_EXPORT, "producer_version": "fixture-exporter", "stage": "EXTRACT_FEATURES"},
    }
    annotation = {"synonyms_zh": [], "synonyms_en": [block_id.removeprefix("minecraft:")], "summary_zh": block_id, "summary_en": name_for(block_id), "color_terms": ["yellow"] if block_id.endswith("carpet") else [], "shape_terms": classes, "material_impressions": [], "building_roles": ["roof"] if block_id.endswith("carpet") else ["wall"], "style_tags": [], "avoid_for": [], "confidence": 0.95}
    variant["_fixture_preview"] = preview
    variant["_fixture_mask"] = mask
    variant["_fixture_render_metadata"] = render_metadata
    return variant, feature, annotation


def name_for(block_id: str) -> str:
    return {"minecraft:stone": "Stone", "minecraft:glass": "Glass", "minecraft:yellow_carpet": "Yellow Carpet"}.get(block_id, block_id)


@dataclass(frozen=True, slots=True)
class Fixture:
    root: Path
    release: Path
    current: Path
    release_id: str = RELEASE_ID


def _create_index(path: Path, blocks: list[dict[str, Any]], states: list[dict[str, Any]], variants: list[dict[str, Any]], features: dict[str, dict[str, Any]], annotations: dict[str, dict[str, Any]], *, version: int = 2, force_like: bool = False) -> None:
    connection = sqlite3.connect(path)
    connection.executescript("""
    PRAGMA foreign_keys=ON;
    CREATE TABLE schema_meta(format_version INTEGER PRIMARY KEY);
    CREATE TABLE blocks(block_id TEXT PRIMARY KEY,minecraft_version TEXT NOT NULL,translation_key TEXT,name_zh TEXT,name_en TEXT,default_state_id TEXT NOT NULL,machine_facts_json TEXT NOT NULL,record_json TEXT NOT NULL);
    CREATE TABLE states(state_id TEXT PRIMARY KEY,block_id TEXT NOT NULL REFERENCES blocks(block_id),properties_json TEXT NOT NULL,is_default INTEGER NOT NULL,record_json TEXT NOT NULL);
    CREATE TABLE visual_variants(variant_id TEXT PRIMARY KEY,block_id TEXT NOT NULL REFERENCES blocks(block_id),canonical_state_id TEXT NOT NULL REFERENCES states(state_id),represented_state_ids_json TEXT NOT NULL,preview_path TEXT NOT NULL,mask_path TEXT NOT NULL,render_metadata_path TEXT NOT NULL,image_sha256 TEXT NOT NULL,mask_sha256 TEXT NOT NULL,render_metadata_sha256 TEXT NOT NULL,candidate_qualification TEXT NOT NULL,warnings_json TEXT NOT NULL,record_json TEXT NOT NULL,feature_json TEXT NOT NULL);
    CREATE TABLE annotations(variant_id TEXT PRIMARY KEY REFERENCES visual_variants(variant_id),semantic_json TEXT NOT NULL);
    CREATE INDEX states_block_id_idx ON states(block_id);
    CREATE INDEX visual_variants_block_id_idx ON visual_variants(block_id);
    CREATE INDEX visual_variants_qualification_idx ON visual_variants(candidate_qualification);
    """)
    connection.execute("INSERT INTO schema_meta(format_version) VALUES (?)", (version,))
    for block in blocks:
        connection.execute("INSERT INTO blocks VALUES (?,?,?,?,?,?,?,?)", (block["block_id"], "26.2", block["translation_key"], block["official_names"]["zh_cn"], block["official_names"]["en_us"], block["default_state_id"], _json(block["machine_facts"]), _json(block)))
    for state in states:
        connection.execute("INSERT INTO states VALUES (?,?,?,?,?)", (state["state_id"], state["block_id"], "{}", 1, _json(state)))
    for variant in variants:
        render = variant["render"]
        connection.execute("INSERT INTO visual_variants VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)", (variant["variant_id"], variant["block_id"], variant["canonical_state_id"], _json(variant["represented_state_ids"]), f"previews/minecraft/{variant['variant_id'].removeprefix('minecraft:')}/preview.png", f"previews/minecraft/{variant['variant_id'].removeprefix('minecraft:')}/mask.png", f"previews/minecraft/{variant['variant_id'].removeprefix('minecraft:')}/render.json", render["image_sha256"], render["mask_sha256"], render["render_metadata_sha256"], variant["candidate_qualification"], _json(variant["warnings"]), _json({key: value for key, value in variant.items() if not key.startswith("_fixture_")}), _json(features[variant["variant_id"]])))
        connection.execute("INSERT INTO annotations VALUES (?,?)", (variant["variant_id"], _json(annotations[variant["variant_id"]])))
    try:
        if force_like:
            raise sqlite3.OperationalError
        connection.execute("CREATE VIRTUAL TABLE search_fts USING fts5(variant_id UNINDEXED,normalized_text,tokenize='trigram')")
        fts = True
    except sqlite3.OperationalError:
        connection.execute("CREATE TABLE search_text(variant_id TEXT PRIMARY KEY,normalized_text TEXT NOT NULL)")
        fts = False
    for variant in variants:
        block = next(item for item in blocks if item["block_id"] == variant["block_id"])
        text_parts: list[str] = []
        names = block["official_names"]
        text_parts.extend(value for value in (names.get("zh_cn"), names.get("en_us")) if isinstance(value, str))
        text_parts.extend(str(value) for value in variant["machine_facts"].get("machine_tags", []))
        text_parts.extend(str(value) for value in variant["machine_facts"].get("geometry", {}).get("geometry_classes", []))
        semantic = annotations[variant["variant_id"]]
        for key in SEMANTIC_LIST_FIELDS + SEMANTIC_SCALAR_FIELDS:
            value = semantic.get(key)
            if isinstance(value, list):
                text_parts.extend(str(item) for item in value)
            elif isinstance(value, str):
                text_parts.append(value)
        text = normalize_text(" ".join(sorted(set(text_parts), key=lambda value: value.encode("utf-8"))))
        connection.execute("INSERT INTO " + ("search_fts" if fts else "search_text") + "(variant_id,normalized_text) VALUES (?,?)", (variant["variant_id"], text))
    connection.commit()
    connection.close()


def build_fixture(root: Path, *, index_version: int = 2, force_like: bool = False) -> Fixture:
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    release = root / "releases" / "26.2" / RELEASE_ID
    (release / "previews").mkdir(parents=True)
    blocks = [_block("minecraft:stone", "石头", "Stone", "minecraft:stone"), _block("minecraft:glass", "玻璃", "Glass", "minecraft:glass"), _block("minecraft:yellow_carpet", "黄色地毯", "Yellow Carpet", "minecraft:yellow_carpet")]
    values = [("minecraft:stone", _behavior(transparent=False, redstone=False), _shape(HASH), ["full_cube"], ["full_cube", "stone"]), ("minecraft:glass", _behavior(transparent=True, redstone=False), _shape("sha256:" + "b" * 64), [], ["glass"]), ("minecraft:yellow_carpet", _behavior(transparent=False, redstone=False), _shape("sha256:" + "c" * 64, full=False, height=0.0625), ["horizontal_sheet", "thin"], ["carpet", "horizontal_sheet", "thin"])]
    states: list[dict[str, Any]] = []
    variants: list[dict[str, Any]] = []
    features: dict[str, dict[str, Any]] = {}
    annotations: dict[str, dict[str, Any]] = {}
    block_positions = {"minecraft:stone": 0, "minecraft:glass": 1, "minecraft:yellow_carpet": 2}
    for block_id, behavior, shape, classes, tags in values:
        state = _state(block_id, block_id, behavior, shape, variant_id=block_id)
        variant, feature, annotation = _variant(block_id, block_id, behavior, shape, classes=classes, tags=tags)
        blocks[block_positions[block_id]]["machine_facts"] = {"has_item": True, "has_block_entity": False}
        states.append(state)
        variants.append(variant)
        features[block_id] = feature
        annotations[block_id] = annotation
        target = release / "previews" / "minecraft" / block_id.removeprefix("minecraft:")
        target.mkdir(parents=True, exist_ok=True)
        (target / "preview.png").write_bytes(variant.pop("_fixture_preview"))
        (target / "mask.png").write_bytes(variant.pop("_fixture_mask"))
        (target / "render.json").write_bytes(_canonical(variant.pop("_fixture_render_metadata")))
    _create_index(release / "index.sqlite3", blocks, states, variants, features, annotations, version=index_version, force_like=force_like)
    manual = {"format_version": 1, "release_id": RELEASE_ID, "version": "26.2", "manual_overrides": [], "skip_reviews": [], "qualification_reviews": []}
    (release / "manual-overrides.json").write_bytes(_canonical(manual))
    snapshot = {"adapter": "openai_responses", "profile_id": "default", "model_id": "fixture-model", "base_url_stable_id": "http://127.0.0.1:8766/v1", "secret_reference": "env:OPENAI_API_KEY", "prompt_version": "prompt.v1", "request_envelope_schema_id": "provider-batch-envelope.v1", "wire_schema_ids": {"offline_annotation": "annotation-batch-output.v1", "query_spec": "query-spec-output.v1", "visual_rerank": "rerank-output.v1"}, "search_ranking_version": "search-ranking.v1"}
    evidence_by_code = {
        "REGISTRY_COVERAGE_100": ["index.sqlite3"],
        "BLOCK_VARIANT_OR_AUDITED_SKIP": ["manual-overrides.json", "index.sqlite3"],
        "EXCLUDED_QUALIFICATION_REVIEW_VALID": ["manual-overrides.json"],
        "IMAGE_READABLE_AND_HASHED": ["previews/minecraft/stone/preview.png"],
        "LEGAL_STATE_VALID": ["index.sqlite3"],
        "MACHINE_SCHEMA_VALID": ["manifest.json"],
        "AI_SCHEMA_VALID": ["manifest.json"],
        "OVERRIDE_REFERENCES_VALID": ["manual-overrides.json"],
        "NO_FALSE_IDS": ["index.sqlite3"],
        "HIGH_REVIEW_ZERO": ["quality_report.json"],
        "FTS_READY": ["index.sqlite3"],
        "RELEASE_HASH_MANIFEST": ["manifest.json", "checksums.sha256"],
    }
    quality = {
        "format_version": 1,
        "report_kind": "release",
        "release_id": RELEASE_ID,
        "release_build_id": RELEASE_BUILD_ID,
        "run_id": RUN_ID,
        "minecraft_version": "26.2",
        "status": "passed",
        "snapshot_fingerprint": HASH,
        "items": [
            {
                "code": code,
                "status": "passed",
                "blocking": True,
                "observed_count": 2 if code == "RELEASE_HASH_MANIFEST" else 1,
                "error_code": None,
                "evidence": evidence_by_code[code],
            }
            for code in CHECK_CODES
        ],
        "built_at": "2026-08-18T12:00:00Z",
    }
    (release / "quality_report.json").write_bytes(_canonical(quality))
    index_hash = _hash((release / "index.sqlite3").read_bytes())
    manifest = {"schema_version": "release-manifest.v1", "release_id": RELEASE_ID, "minecraft_version": "26.2", "source_export_id": SOURCE_EXPORT, "source_export_manifest_sha256": HASH, "toolchain_lock_sha256": HASH, "schemas_inventory_path": "schemas.sha256", "provider_snapshot": snapshot, "functional_inputs": {"fixture/input": HASH}, "functional_artifacts": {"index.sqlite3": index_hash}, "quality_report_path": "quality_report.json", "quality_report_sha256": _hash((release / "quality_report.json").read_bytes()), "fts_mode": "trigram" if any("search_fts" in row[0] for row in sqlite3.connect(release / "index.sqlite3").execute("SELECT name FROM sqlite_master WHERE type='table'") ) else "normalized_like"}
    manifest_bytes = _canonical(manifest)
    (release / "manifest.json").write_bytes(manifest_bytes)
    release_json = {"schema_version": "release.v1", "release_id": RELEASE_ID, "minecraft_version": "26.2", "built_at": "2026-08-18T12:00:00Z", "source_export_id": SOURCE_EXPORT, "manifest_sha256": _hash(manifest_bytes), "record_schema_versions": {"block": "block-record.v1", "state": "state-record.v1", "variant": "visual-variant-record.v1", "annotation": "annotation-record.v1", "manual_override": "manual-override.v1", "skip_review": "skip-review.v1", "qualification_review": "qualification-review.v1"}, "quality_report_path": "quality_report.json", "immutable": True}
    (release / "release.json").write_bytes(_canonical(release_json))
    schema_lines = []
    for schema_id in ("block-record.v1", "state-record.v1", "visual-variant-record.v1", "annotation-record.v1", "release-manifest.v1", "release.v1", "current-pointer.v1"):
        path = Path(__file__).parents[2] / "schemas" / "workspace" / f"{schema_id}.json"
        schema_lines.append(f"{_raw_hash(path.read_bytes())}  {schema_id}  schemas/workspace/{schema_id}.json\n")
    (release / "schemas.sha256").write_bytes("".join(sorted(schema_lines, key=lambda line: line.split("  ")[1].encode("utf-8"))).encode("ascii"))
    files = sorted(path.relative_to(release).as_posix() for path in release.rglob("*") if path.is_file() and path.name != "checksums.sha256")
    (release / "checksums.sha256").write_bytes("".join(f"{_raw_hash((release / ref).read_bytes())}  {ref}\n" for ref in files).encode("ascii"))
    pointer = {"schema_version": "current-pointer.v1", "versions": {"26.2": {"release_id": RELEASE_ID, "minecraft_version": "26.2", "relative_path": f"releases/26.2/{RELEASE_ID}", "manifest_sha256": _hash(manifest_bytes)}}, "default_minecraft_version": "26.2", "updated_at": "2026-08-18T12:00:00Z"}
    current = root / "current.json"
    current.write_bytes(_canonical(pointer))
    return Fixture(root, release, current)


__all__ = ["Fixture", "build_fixture"]
