plugins {
    id 'net.fabricmc.fabric-loom'
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = 'Fabric'
        url = uri('https://maven.fabricmc.net/')
    }
    mavenCentral()
}

dependencyLocking {
    lockAllConfigurations()
    lockFile = layout.projectDirectory.file('gradle/dependency-locks.lockfile')
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

processResources {
    inputs.property 'version', project.version

    from(rootProject.file('schemas/exporter')) {
        into 'schemas/exporter'
        include '*.json'
    }

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}
